
global:
  domain: ""
  # Used by ingresses - forces http -> https redirect
  # Possible values: [ "true", "false" ]
  force_ssl_redirect: "true"
  # Set to "true" only for main production environment.
  # Setting to "false" disables Sentry and HotJar tracking
  # Possible values: [ "true", "false" ]
  production: "false"
  registry: ""
  analytics:
    port: "8086"

ingress:
  enabled: true

docs:
  image: ""
  domain: "docs"
  redirect_domain: "documentation"
  port: "80"
  resources:
    requests:
      cpu: "0.1"
      memory: "256Mi"
    limits:
      cpu: "0.1"
      memory: "256Mi"
  replicas: 1
  nodeSelector: {}
  tolerations: []
  # Heap analytics account
  heapId: ""
